queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Put me in default queue
    conditions:
      - base=main
      - label=queue
    actions:
      queue:
        name: default
  - name: test rebase
    conditions:
      - label=rebase
    actions:
      rebase:
      label:
        remove:
          - rebase
