name: Continuous Integration
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Fake JUnit Report
        run: |
          cat <<EOF > report.xml
          <testsuites>
            <testsuite name="ExampleTestSuite" tests="1" failures="0" errors="0" skipped="0">
              <testcase classname="example.TestClass" name="testExample" time="0.001"/>
            </testsuite>
          </testsuites>
          EOF

      - name: Print JUnit Report Content
        shell: bash
        run: |
          cat report.xml

      - name: Mergify JUnit XML Upload
        if: always()
        uses: mergifyio/gha-ci-issues@v1
